version: '3'

services:
  web:
    build: 
      context: .
      args:
        - DJANGO_SUPERUSER_PHONE=${DJANGO_SUPERUSER_PHONE}
        - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
        - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
        - RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
        - RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}
        - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
        - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
        - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
        
    ports:
      - "8000:8000"
    volumes:
      - .:/donations
    
