# Generated by Django 5.0.1 on 2024-01-08 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationtype",
            name="status",
            field=models.CharField(default="Pending", max_length=999999),
        ),
        migrations.AlterField(
            model_name="donationtype",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="payment_gateway",
            field=models.CharField(
                choices=[
                    ("Stripe_payment", "Stripe_payment"),
                    ("Razorpay_payment", "Razorpay_payment"),
                ],
                default="Stripe_payment",
                max_length=50,
            ),
        ),
    ]
